### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by nfacha** [LINKIWI/cloudflare-ddns-client#22]
Unable to update the IP, following error happens:

```
root@master:~# cloudflare-ddns --update-now
From cffi callback <function _verify_callback at 0x7600d430>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
Traceback (most recent call last):
  File "/usr/local/bin/cloudflare-ddns", line 193, in <module>
    main()
  File "/usr/local/bin/cloudflare-ddns", line 183, in main
    external_ip = get_external_ip()
  File "/usr/local/bin/cloudflare-ddns", line 91, in get_external_ip
    return requests.get(EXTERNAL_IP_QUERY_API, timeout=6).json()['ip']
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

```

I'm able to `curl https://api.ipify.org` with no errors, also the API SSL is fine

I'm able to fix this bt running `sudo python -m easy_install --upgrade pyOpenSSL` so it might be using incorrect versions by default

**Comment by zaanposni** [comment]
Guess we have to take a look at our requirements.txt, it seems a bit off anyway.
