### ISSUE TITLE
Not working.  ImportError.

### ISSUE THREAD

**Issue by doughnet** [LINKIWI/cloudflare-ddns-client#56]
After doing a git clone and make install as root ran the command: **cloudflare-ddns --configure**

`
Traceback (most recent call last):
  File "/usr/local/bin/cloudflare-ddns", line 10, in <module>
    from tld import get_fld
  File "/usr/local/lib/python2.7/dist-packages/tld/__init__.py", line 7, in <module>
    from .utils import get_fld, get_tld, get_tld_names, is_tld, parse_tld, Result, update_tld_names
  File "/usr/local/lib/python2.7/dist-packages/tld/utils.py", line 10, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
`

Python 2.7.17
Python 3.7.5
pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

which output:
/usr/local/bin/cloudflare-ddns

OS: Ubuntu 20.04 LXC VPS

**Comment by timbrd** [comment]
Same problem here, running on Raspbian 10 (Debian Buster):

```bash
$ ./cloudflare-ddns --configure
Traceback (most recent call last):
  File "./cloudflare-ddns", line 10, in <module>
    from tld import get_fld
  File "/home/pi/.local/lib/python2.7/site-packages/tld/__init__.py", line 7, in <module>
    from .utils import get_fld, get_tld, get_tld_names, is_tld, parse_tld, Result, update_tld_names
  File "/home/pi/.local/lib/python2.7/site-packages/tld/utils.py", line 10, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
```

**Comment by timbrd** [comment]
@doughnet Found a workaround to the problem. You can install the python module on Debian Buster with 

```bash
$ apt install python-backports.functools-lru-cache
```
